### ISSUE TITLE
Storage plugins fails when empty if porter storage migrate has not been run

### ISSUE THREAD

**Issue by simongdavies** [getporter/azure-plugins#26]
Steps to reproduce

Create a new storage account and container
set environment variable `AZURE_STORAGE_CONNECTION_STRING` to the connection string for the new storage account
Configure config.toml to use azure storage
Run `porter list`

Fails with the following error:

`Error: could not list installations: The schema of Porter's data is in an older format than supported by this version of Porter.
Refer to https://porter.sh/storage-migrate for more information and instructions to back up your data.
Once your data has been backed up, run the following command to perform the migration:`

    porter storage migrate

There should be no need for the user to run porter storage migrate in this case.

Porter Version:

porter v0.28.1 (dd9056f3)

Plugin Version:

azure v0.9.0 (d91c4f3) by Porter Authors

**Comment by carolynvs** [comment]
This has been fixed by #27 and released in 0.9.1
