### ISSUE TITLE
did azure change some auth or format? 

### ISSUE THREAD

**Issue by squillace** [getporter/azure-plugins#39]
a user reported "I’ve got this down to an issue with the latest Azure CLI release – 2.30.0 , if I downgrade the Azure CLI all is good. So either the Az CLI team have a bug, or there is a breaking change that is preventing porter from operating correctly."

Let's have a look at this.

<guid>: Error context message = Error: could not save the pending action's status, the bundle was not executed:could not read storage schema document:Failed to login with Azure CLI:Error parsing Token Expiration Date \"\":Error parsing expiration date \"\". 

 

CloudShell Error: parsing time \"\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"\" as \"2006\"

 

CLI Error: parsing time \"\" as \"2006-01-02 15:04:05.999999\": cannot parse \"\" as \"2006\"

**Comment by carolynvs** [comment]
@squillace Looks like this was finally fixed in the az CLI. https://github.com/Azure/azure-cli/pull/20219

Since we don't distribute the az cli in this plugin, I _think_ there's nothing for us to do? The users just need to update their az cli to the latest version. Does that sound right?
