### ISSUE TITLE
Cleanup publish mage target

### ISSUE THREAD

**Issue by carolynvs** [getporter/azure-plugins#42]
In a follow-up, let's remove the argument and switch this repo over to use mage 100% of the time, removing the makefile. You can look at the kubernetes plugin magefile as an example.

Long term it would be great to have an equivalent plugins/magefile.go in the magefiles repository just like we have with mixins, so that the entire magefile is easy to manage without requiring a lot of customization.

_Originally posted by @carolynvs in https://github.com/getporter/azure-plugins/pull/41#discussion_r867202151_

**Comment by kichristensen** [comment]
Seems to have been done in #45
