### ISSUE TITLE
Sensitive snake_case porter parameters fails to deploy when using azure.keyvault plugin

### ISSUE THREAD

**Issue by anatbal** [getporter/azure-plugins#51]
## Describe the bug
We are using porter version 1.0.0 with the Azure keyvault secrets plugin activated. We have all our parameters  inside the porter.yaml config as snake cased, but once we mark it as sensitive like this:
```yaml
 -name: some_password
  sensitive: true
```
 we are having this error when trying to run porter install with the bundle:
`failed to set secret for key XXX-some_password in azure-keyvault: keyvault.BaseClient#SetSecret: Invalid input: autorest/validation: validation failed: parameter=secretName constraint=Pattern value=\"0 XXX-some_password\" details: value doesn't match pattern ^[0-9a-zA-Z-]+$`

This bug occurs since the name of the variable is "some_password" and the keyvault naming convention **does not allow underscores** (_) in the secret name. 

## To Reproduce
1. Activate the Azure keyvault secrets plugin.
2. Use a porter.yaml with a senstive **snake cased** param inside.
3. Build the bundle
4. Run porter install
5. See error as specified above.

## Expected behavior
There should be a way to overcome this and still support snake_case parameters without having to change them all to camelCased.

## Version
Copy the output of `porter version` below

porter v1.0.4 (e3a2a5ef)

**Comment by carolynvs** [comment]
@anatbal I am moving this issue to the azure-plugins repository where the change needs to be made. This may have broken your link to this issue from the Azure TRE repo.

**Comment by carolynvs** [comment]
Here is the proposed fix, in case you'd like to help review or test the change. https://github.com/getporter/azure-plugins/pull/59
