### ISSUE TITLE
Hardcoded vault url prevents usage in a gov cloud

### ISSUE THREAD

**Issue by tamirkamara** [getporter/azure-plugins#57]
The linked line makes an assumption that the vault is in the commercial cloud and that prevents usage in a gov cloud (like US):
https://github.com/getporter/azure-plugins/blob/main/pkg/azure/keyvault/store.go#L43

**Comment by carolynvs** [comment]
@tamirkamara I just wanted to confirm that your team is planning on submitting a patch. If not, let me know so that I can prioritize appropriately.

**Comment by tamirkamara** [comment]
Yes @carolynvs, we do plan to do this in the next couple of weeks.
BTW, this isn't just the parameters but also the go dependencies so we might need some help... but we'll cross that bridge when we get to it.

**Comment by carolynvs** [comment]
Closed by #60
