### ISSUE TITLE
Investigate configuration strategy

### ISSUE THREAD

**Issue by carolynvs** [getporter/azure-plugins#8]
Right now we have multiple ways to configure the plugin:

* Use the default storage connection string env var for blob storage
* Specify an alt storage connection string env var
* Use the default service principal env vars for key vault
* Specify a prefix to apply to the the service principal env vars

And looming in the wings is being able to log in with az login (MSI) which I have partway implemented.

Investigate if we can bring this down a bit so that there aren't so many ways to do this, it's confusing to have one way to auth for storage and another for everything else.

See https://github.com/deislabs/porter-azure-plugins/pull/6#discussion_r374835663, as part of this let's try to cleanup the config struct if we can as well.

**Comment by kichristensen** [comment]
Closed since now secrets plugin is the only configuration available
